### PR TITLE
For a Shelly Roller Shutter it is now possible to specify the relative opening of the shutter.

### PR DESCRIPTION
**Pull request by holger-dunst**
Hello Tim,

thanks for your feedback.
I have made the changes.

Regards,

Holger

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Damn, I forget to mention one thing.
A `LevelProperty` needs min/max values.
I'll add them after I merged this.

**Comment by tim-hellhake** [comment]
@rmeissn FYI

**Comment by rmeissn** [comment]
Some Feedback about this PR and the roller shutter mode in general:
- Setting a level is very useful, many thanks!
- I'd expect that "Relative roller shutter position" tells me how far it is closed. Actually it tells me how far it has opened. This might be improved by a more precise text, like "Opening level in %", or invert it and name it "Closing level in %". For me a closing level is more intuitive than an opening level.
- The number of the relative level won't update on other actions. E.g. I've fully opened the shutter by the open action, but the relative level is still on 88.
- I see 3 Power statements: Power 0, Power 1, Power all. Even though I know where the three levels come from, only "Power all" is relevant for the roller shutter mode (in contrast to relay mode)

**Comment by holger-dunst** [comment]
Yeah, you're right. The displayed position corresponds one to one to the value of the Shelly Roller Shutter, which is also displayed in the Shelly app and returned by the REST-Api. Therefore, I don't want to invert the value to confuse the users (including me) who already know this behaviour. It would be better to adjust the text. 

The adapter is based on a different JavaScript library "alexryd/node-shellies", that handles the communication with the devices. Unfortunately I have not found a way to get the current values of a device, e.g. when starting the adapter. The values are only updated when the device sends an event.
I have four Shelly Roller Shutters and for mine, after the roller shutter has finished performing the action, the value is updated in the UI. Are there any error messages in your log?

**Pull request merged**
